quarkus:
  http:
    port: ${PORT:8080}
    host: 0.0.0.0
  profile: [{dev}]
  devservices:
    enabled: false
  hibernate-orm:
    database:
      generation: none # Default to none for safety
    sql-load-script: import.sql
    log:
      sql: true
  mailer:
    from: "OWNC <ownc.mailer@gmail.com>"
    host: "smtp.gmail.com"
    port: 587
    username: "ownc.mailer@gmail.com"
    password: "${MAILER_PASSWORD}"
    start-tls: REQUIRED
    mock: false
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:quarkus_user}
    password: ${DB_PASSWORD:quarkus_password}
    reactive:
      url: ${DB_URL:postgresql://localhost:5433/ownc_db}
    devservices:
      enabled: false
  redis:
    hosts: ${REDIS_URL:redis://localhost:6379}
    devservices:
      enabled: false
  log:
    level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"

"%prod":
  quarkus:
    hibernate-orm:
      database:
        generation: none # Never drop-and-create in prod
    dev-ui:
      enabled: false
    http:
      port: 8080
      host: 0.0.0.0
    container-image:
      group: "us-central1-docker.pkg.dev/subtle-reserve-456823-n1/uploader-repo"
      name: "uploader-backend"
      tag: "latest"
      builder: "jib"
    datasource:
      port: 5433
      db-name: ownc_db
      username: quarkus_user
      password: quarkus_password
    log:
      level: INFO
      # Desactivamos logs a archivo en prod para evitar problemas de permisos
      file:
        enable: false
  mp:
    jwt:
      verify:
        issuer: ${PROD_DOMAIN}
        publickey:
          value: ${PUBLIC_KEY}

"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create
    http:
      port: 8080
  mp:
    jwt:
      verify:
        issuer: ${DEV_DOMAIN}
        publickey:
          value: ${PUBLIC_KEY}

smallrye:
  jwt:
    sign:
      key:
        value: ${PRIVATE_KEY}
google:
  cloud:
    project-id: "subtle-reserve-456823-n1"
    # En Cloud Run usaremos la identidad de la instancia, no un archivo de key si es posible
    # Pero si lo necesitan, deben asegurarse de que el archivo existe
    credentials:
      file-path: ${GOOGLE_APPLICATION_CREDENTIALS:keys/subtle-reserve-456823-n1-729247d0e46c.json}
mi:
  bucket:
    name: "canaris"